export const HANDLE_AUTHENTICATION = "HANDLE_AUTHENTICATION";
export const FETCH_STREAMS = "FETCH_STREAMS";
export const FETCH_STREAM = "FETCH_STREAM";
export const CREATE_STREAM = "CREATE_STREAM";
export const UPDATE_STREAM = "UPDATE_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";